# Generated by Django 3.2.9 on 2021-11-23 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_rename_product_products'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
