# Generated by Django 3.2.9 on 2021-11-21 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_rename_product_products'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='Products',
        ),
    ]
